name: Rust static build Linux
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: build Linux static binary
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      BINARY_NAME: echtvar
    steps:
    - uses: actions/checkout@v4
    - name: Set build version
      id: version
      shell: bash
      run: |
        VERSION="$(grep 'version =' Cargo.toml -m 1 | sed 's@version =@@' | xargs)"
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "::notice::publish build version $VERSION"
    - name: Install musl tools
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools musl-dev cmake
    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build Linux x86 static binary
      env:
        CC: /usr/bin/x86_64-linux-musl-gcc
        CXX: /usr/bin/x86_64-linux-musl-gcc
      run: cargo build --target x86_64-unknown-linux-musl --release
    - name: Upload linux binary to release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.RELEASE_VERSION }}
        name: v${{ env.RELEASE_VERSION }}
        files: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
